token:
    key: Cj{U8]q)n}xQ7c(01;uS
    algorithm: HS256
    header: productivity
    exp: 3600
api:
    version: v1
    host: localhost
    port: 8080
headers:
    origin: api.productivity.researchdev.xyz